// Code generated by 'go run ./gen'; DO NOT EDIT

package day04

import "github.com/spf13/cobra"

func AddCommandsTo(root *cobra.Command) {
	day := &cobra.Command{
		Use:     "04",
		Aliases: []string{"4"},
		Short:   "Problems for Day 4",
	}

	day.AddCommand(aCommand())
	day.AddCommand(bCommand())

	root.AddCommand(day)
}
