// Code generated by 'go run ./gen'; DO NOT EDIT

package day06

import "github.com/spf13/cobra"

func AddCommandsTo(root *cobra.Command) {
	day := &cobra.Command{
		Use:     "06",
		Aliases: []string{"6"},
		Short:   "Problems for Day 6",
	}

	day.AddCommand(aCommand())
	day.AddCommand(bCommand())

	root.AddCommand(day)
}
