// Code generated by 'go run ./gen'; DO NOT EDIT

package cmd

import (
	"fmt"
	"time"

	"github.com/pkg/profile"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/nlowe/aoc2025/challenge/day01"
	"github.com/nlowe/aoc2025/challenge/day02"
	"github.com/nlowe/aoc2025/challenge/day03"
	"github.com/nlowe/aoc2025/challenge/day04"
	"github.com/nlowe/aoc2025/challenge/day05"
	"github.com/nlowe/aoc2025/challenge/day06"
	"github.com/nlowe/aoc2025/challenge/day07"
	"github.com/nlowe/aoc2025/challenge/day08"
	"github.com/nlowe/aoc2025/challenge/day09"
	"github.com/nlowe/aoc2025/challenge/day10"
	"github.com/nlowe/aoc2025/challenge/example"
)

func addDays(root *cobra.Command) {
	example.AddCommandsTo(root)
	day01.AddCommandsTo(root)
	day02.AddCommandsTo(root)
	day03.AddCommandsTo(root)
	day04.AddCommandsTo(root)
	day05.AddCommandsTo(root)
	day06.AddCommandsTo(root)
	day07.AddCommandsTo(root)
	day08.AddCommandsTo(root)
	day09.AddCommandsTo(root)
	day10.AddCommandsTo(root)
}

type prof interface {
	Stop()
}

func NewRootCommand() *cobra.Command {
	var (
		start    time.Time
		profiler prof
	)

	result := &cobra.Command{
		Use:     "aoc2025",
		Short:   "Advent of Code 2022 Solutions",
		Long:    "Golang implementations for the 2022 Advent of Code problems",
		Example: "go run main.go 1 a -i ./challenge/day1/input.txt",
		Args:    cobra.ExactArgs(1),
		PersistentPreRun: func(_ *cobra.Command, _ []string) {
			if viper.GetBool("profile") {
				profiler = profile.Start()
			}

			start = time.Now()
		},
		PersistentPostRun: func(_ *cobra.Command, _ []string) {
			if profiler != nil {
				profiler.Stop()
			}

			fmt.Println("Took", time.Since(start))
		},
	}

	addDays(result)

	flags := result.PersistentFlags()

	flags.StringP("input", "i", "", "Input File to read. If not specified, assumes ./challenge/dayN/input.txt for the currently running challenge")
	flags.Bool("profile", false, "Profile implementation performance")

	_ = viper.BindPFlags(flags)

	return result
}
