// Code generated by 'go run ./gen'; DO NOT EDIT

package day05

import "github.com/spf13/cobra"

func AddCommandsTo(root *cobra.Command) {
	day := &cobra.Command{
		Use:     "05",
		Aliases: []string{"5"},
		Short:   "Problems for Day 5",
	}

	day.AddCommand(aCommand())
	day.AddCommand(bCommand())

	root.AddCommand(day)
}
