// Code generated by 'go run ./gen'; DO NOT EDIT

package day01

import "github.com/spf13/cobra"

func AddCommandsTo(root *cobra.Command) {
	day := &cobra.Command{
		Use:     "01",
		Aliases: []string{"1"},
		Short:   "Problems for Day 1",
	}

	day.AddCommand(aCommand())
	day.AddCommand(bCommand())

	root.AddCommand(day)
}
