// Code generated by 'go run ./gen'; DO NOT EDIT

package day03

import "github.com/spf13/cobra"

func AddCommandsTo(root *cobra.Command) {
	day := &cobra.Command{
		Use:     "03",
		Aliases: []string{"3"},
		Short:   "Problems for Day 3",
	}

	day.AddCommand(aCommand())
	day.AddCommand(bCommand())

	root.AddCommand(day)
}
